
package com.xt.touch.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MyServiceImpl", targetNamespace = "http://ws.touch.xt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyServiceImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.touch.xt.com/", className = "com.xt.touch.ws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.touch.xt.com/", className = "com.xt.touch.ws.AddResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findSendBoxByPage", targetNamespace = "http://ws.touch.xt.com/", className = "com.xt.touch.ws.FindSendBoxByPage")
    @ResponseWrapper(localName = "findSendBoxByPageResponse", targetNamespace = "http://ws.touch.xt.com/", className = "com.xt.touch.ws.FindSendBoxByPageResponse")
    public String findSendBoxByPage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Integer arg2);

}
