
package com.xt.touch.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MyService", targetNamespace = "http://ws.touch.xt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyService {


    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addResult", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.touch.xt.com/", className = "com.xt.touch.ws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.touch.xt.com/", className = "com.xt.touch.ws.AddResponse")
    public int add(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param pagesize
     * @param userId
     * @param offset
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sendbox", targetNamespace = "")
    @RequestWrapper(localName = "findSendBoxByPage", targetNamespace = "http://ws.touch.xt.com/", className = "com.xt.touch.ws.FindSendBoxByPage")
    @ResponseWrapper(localName = "findSendBoxByPageResponse", targetNamespace = "http://ws.touch.xt.com/", className = "com.xt.touch.ws.FindSendBoxByPageResponse")
    public String findSendBoxByPage(
        @WebParam(name = "userId", targetNamespace = "")
        String userId,
        @WebParam(name = "offset", targetNamespace = "")
        Integer offset,
        @WebParam(name = "pagesize", targetNamespace = "")
        Integer pagesize);

}
